package db_restaurante;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * his method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEliminarPlatos = new javax.swing.JButton();
        btnAgregarPlatos = new javax.swing.JButton();
        btnPlatos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPlatos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnBebidas = new javax.swing.JButton();
        btnAgregarBebida = new javax.swing.JButton();
        btnEliminarBebidas = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBebidas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminarPlatos.setText("Eliminar");
        btnEliminarPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPlatosActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarPlatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 120, -1));

        btnAgregarPlatos.setText("Agregar");
        btnAgregarPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPlatosActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarPlatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 120, -1));

        btnPlatos.setText("Ver Platos");
        btnPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlatosActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 120, 30));

        tablaPlatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cod_Plato", "Nombre", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaPlatos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 155));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Platos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        btnBebidas.setText("Ver Bebidas");
        btnBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBebidasActionPerformed(evt);
            }
        });
        getContentPane().add(btnBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 120, -1));

        btnAgregarBebida.setText("Agragar");
        btnAgregarBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarBebidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarBebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 120, -1));

        btnEliminarBebidas.setText("Eliminar");
        btnEliminarBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarBebidasActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 120, -1));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 99, -1));

        tablaBebidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cod_Bebida", "Nombre", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaBebidas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 158));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bebidas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo 3.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlatosActionPerformed
        DefaultTableModel modelo = new DefaultTableModel();

        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurante", "root", "");
            PreparedStatement pst = cn.prepareStatement("SELECT * FROM platos");
            ResultSet rs = pst.executeQuery();
            modelo.setColumnIdentifiers(new Object[]{"ID_Plato", "Nombre", "Precio"});

            try {
                while (rs.next()) {
                    modelo.addRow(new Object[]{rs.getString("Cod_Plato"), rs.getString("Nombre"), rs.getString("Precio")});
                }
                tablaPlatos.setModel(modelo);
            } catch (Exception ex) {
                System.out.println(ex);
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnPlatosActionPerformed

    private void btnEliminarPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPlatosActionPerformed
        String id = JOptionPane.showInputDialog(null, "Ingrese el código del plato");
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurante", "root", "");
            PreparedStatement pst = cn.prepareStatement("DELETE FROM platos WHERE Cod_Plato=?");
            pst.setString(1, id);
            pst.executeUpdate();

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnEliminarPlatosActionPerformed

    private void btnAgregarPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPlatosActionPerformed
        String nombre, precio;
        nombre = JOptionPane.showInputDialog(null, "Ingrese el nombre del plato");
        precio = JOptionPane.showInputDialog(null, "Ingrese el precio del plato");
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurante", "root", "");
            PreparedStatement pst = cn.prepareStatement("INSERT INTO platos VALUES (?,?,?)");
            pst.setString(1, "0");
            pst.setString(2, nombre);
            pst.setString(3, precio);
            pst.executeUpdate();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnAgregarPlatosActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Principal formulario = new Principal();
        formulario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnEliminarBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarBebidasActionPerformed
        String id = JOptionPane.showInputDialog(null, "Ingrese el código de la bebida");
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurante", "root", "");
            PreparedStatement pst = cn.prepareStatement("DELETE FROM bebidas WHERE Cod_Bebida=?");
            pst.setString(1, id);
            pst.executeUpdate();

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnEliminarBebidasActionPerformed

    private void btnAgregarBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarBebidaActionPerformed
        String nombre, precio;
        nombre = JOptionPane.showInputDialog(null, "Ingrese el nombre de la bebida");
        precio = JOptionPane.showInputDialog(null, "Ingrese el precio de la bebida");
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurante", "root", "");
            PreparedStatement pst = cn.prepareStatement("INSERT INTO bebidas VALUES (?,?,?)");
            pst.setString(1, "0");
            pst.setString(2, nombre);
            pst.setString(3, precio);
            pst.executeUpdate();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnAgregarBebidaActionPerformed

    private void btnBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBebidasActionPerformed
        DefaultTableModel modelo = new DefaultTableModel();
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurante", "root", "");
            PreparedStatement pst = cn.prepareStatement("SELECT * FROM bebidas");
            ResultSet rs = pst.executeQuery();
            modelo.setColumnIdentifiers(new Object[]{"Cod_Bebida", "Nombre", "Precio"});
            try {
                while (rs.next()) {
                    modelo.addRow(new Object[]{rs.getString("Cod_Bebida"), rs.getString("Nombre"), rs.getString("Precio")});
                }
                tablaBebidas.setModel(modelo);
            } catch (Exception ex) {
                System.out.println(ex);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnBebidasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarBebida;
    private javax.swing.JButton btnAgregarPlatos;
    private javax.swing.JButton btnBebidas;
    private javax.swing.JButton btnEliminarBebidas;
    private javax.swing.JButton btnEliminarPlatos;
    private javax.swing.JButton btnPlatos;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTable tablaBebidas;
    private javax.swing.JTable tablaPlatos;
    // End of variables declaration//GEN-END:variables
}
